### ISSUE TITLE
How to Add an Attachment to a Card

### ISSUE THREAD

**Issue by wkonderla** [dillenmeister/Trello.NET#10]
This isn't exactly an issue with the code, but more the documentation. Can you please provide and example on how to add a file attachment to a card. I tried looking at the test fixtures and they use static action ids. I don't know where the action id comes from.

**Comment by dillenmeister** [comment]
Adding attachments is not implemented. A pull request for that would be awesome.

(Most of the tests in Trello.NET are integration tests that makes calls to trello.com. The static IDs are cards, boards etc. that are used by the these tests.)

**Comment by dillenmeister** [comment]
This feature is soon available, have a look at #14.
