### ISSUE TITLE
Read/Write activities on a card

### ISSUE THREAD

**Issue by edmar1960** [dillenmeister/Trello.NET#12]
Maybe I am missing something, but this is the most active area in our site and I can't get access to it.

**Comment by dillenmeister** [comment]
Activities are called Actions in the API. Look at `ITrello.Actions`. For example 

``` csharp
var allActionsForABoard = trello.Actions.AutoPaged().ForBoard(aBoard); 
```

This part of Trello.NET is not complete (there are action types missing), but it might be enough for your needs.

If with "write activities" you mean adding comments you do that with: 

``` csharp
trello.Cards.AddComment(aCard, "The comment");
```

**Comment by edmar1960** [comment]
Ok, got it.

Here is what I ended up doing to enumerate all card action comments.

```
var actions = trello.Actions.ForCard(thisCard);

if (actions.Count() > 0)
```

   {

```
  strMsg += "<p>Activities</p>\n<hr />\n";

  foreach (TrelloNet.CommentCardAction action in actions)

  {

      strMsg += "&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;" + HttpUtility.HtmlEncode(action.Data.Text) + "<br/>\n";

  }
```

   }

Curiously the second for each could not be a “var”, I had to explicitly label it “TrelloNet.CommentCardAction”.

Thanks for the quick response.

**Comment by dillenmeister** [comment]
Does that really work?

I would suggest something like this:

``` csharp
var comments = trello.Actions
    .AutoPaged(Paging.MaxLimit) // This will make sure that you get all comments
    .ForCard(thisCard, new[] { ActionType.CommentCard }) // This will have trello.com return only comments
    .OfType<CommentCardAction>()
    .Select(a => a.Data.Text);

var strMgs = "Activities:<br/>" + string.Join("<br/>", comments);
```

**Comment by edmar1960** [comment]
Actually it did run, there is a proper overload to “CommentCardAction”, but alas I hit a GPFAULT on my first “Move” comment card since it does not contain the “Data.Text” object.

I like your suggestion better than my rewrite which is:

```
var actions = trello.Actions.ForCard(thisCard);

if (actions.Count() > 0)

{

    strMsg += "<p>Activities</p>\n<hr />\n";

    for( int i = 0; i < actions.Count(); i++)

    {

        if (actions.ElementAt(i).ToString().Equals("TrelloNet.CommentCardAction"))

        {

            CommentCardAction crd = (CommentCardAction)actions.ElementAt(i);

            strMsg += "&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;" + HttpUtility.HtmlEncode(crd.Data.Text) + "<br/>\n";

        }

    }

}
```

My code is, as they say in French, is “Le Hack of Hacks” J

Again, thanks for the quick response.

Then again, if ever I want to show the moves as well, I think we have no other choice than above with a few more “if’s” added in.

**Comment by jimpiller** [comment]
I know this has been closed for a year, but someone should do a blog post about getting the comments from a list of cards!!!  I struggled with this for almost a year until i found this posting!!!  Thanks guys, great example!
