### ISSUE TITLE
Suuport for Async Service on certain calls

### ISSUE THREAD

**Issue by edmar1960** [dillenmeister/Trello.NET#13]
I am noticing a long delay on some actions in Trello.  Would be very helpful to support an async service call similar to Twitter:
IAsyncResult result = service.ListTweetsOnHomeTimeline(
(tweets, response) =>
{
    if (response.StatusCode == HttpStatusCode.OK)
    {
      ...
    }
}

**Comment by dillenmeister** [comment]
There is an async API. Look at `trello.Async`.

**Comment by dillenmeister** [comment]
Did you look at Trello.Async? Did it work? Re-open the issue otherwise.

**Comment by edmar1960** [comment]
not yet, it's already in an async thread, but I do need to act on multiple items in this thread as well.  Twitter made it very easy and not optional, so I had to act on that.  Many regards, ed.
