### ISSUE TITLE
TrelloNet and DropNet don't like each other

### ISSUE THREAD

**Issue by edmar1960** [dillenmeister/Trello.NET#16]
I may have to place each of these guys in a separate DLL, but just to log it.  I reference (install) DropNet use it and it works.  I reference (install) TrelloNet and I use it and it works.  I then go back and try a DropNet call and it breaks.  I re-install DropNet and it works.  I go back and try a TrelloNet call and it breaks.  It's our old friend AddDefaultParameter.  Looks like DropNet is using RestSharp 102 and even though it states no dependencies that's what we have.  I will post something at DropNet  as well.

The application terminated with an error.
Method not found: 'Void RestSharp.RestClientExtensions.AddDefaultParameter(RestSharp.IRestClient, System.String, System.Object)'.

**Comment by edmar1960** [comment]
We can close this if you want.  It's definitely a DropNet issue.  I downloaded the latest source from DropNet, referenced the latest RestSharp libraries, compiled and ran.  They are happy together again.  I sent the dev an email and posted an issue on the issue board.  Oskar, you can close if you want, but it is good to record this on both walls.

regards,
ed.

**Comment by dillenmeister** [comment]
Ok, thanks for the info.

Btw, what kind of app are you building using Trello, Dropbox and Twitter etc? Sounds cool. :)
