### ISSUE TITLE
Since.LastVew and Since.Date() returning odd results

### ISSUE THREAD

**Issue by bwinters** [dillenmeister/Trello.NET#17]
This may be just my misunderstanding of how they are supposed to be working, but there isn't any real verbose documentation on it. Is so I apologize ahead of time.

I'm using the following code to get a list of actions that have happened on the board, what I'm looking for are only actions since the last time I queried (Since.LastView), or since the last time my app ran (Since.Date()).

IEnumerable<TrelloNet.Action> actList = t.Actions.ForBoard(new BoardId("50e5fcd7e1d97f0238000337"), since: Since.LastView);
            foreach (TrelloNet.Action act in actList)
                Console.WriteLine(act.Date.AddHours(-7));

This returns way more events than expected. The last change on the board was over 15 hours ago, and I'm getting 13 actions. So the question is what is Since.LastView using to determine what to return?

The next thing is that Actions times are UTC. I'm in Mountian Time (UTC -7), but using Since.Date(DateTime.UtcNow.AddMinutes(-1)) doesn't return something that was modified in the last minute. I made a change in Trello and then checked and had to do (-60) to get results. Is this a bug with the wrapper? with Trello?

**Comment by dillenmeister** [comment]
I don't think the last viewed date is supposed to be automatically set when querying. I see in the documentation that there is a markAsViewed API call (https://trello.com/docs/api/board/index.html#post-1-boards-board-id-markasviewed). It's not implemented in Trello.NET though, 

Regarding the time zone issue, it's probably a bug in Trello.NET.

Pull requests for these things would be highly appreciated. Documentation too (I think it's possible for anyone to edit the Wiki). If you're up for it I'll help with any questions etc. that you might have. If not, I might have some time tomorrow to take a look at it...

**Comment by bwinters** [comment]
I'd appreciate if someone could implement this feature. I'm new to coding and have no idea how to go about implementing this. If I wasn't using it for a work project that has a deadline coming up I would gladly spend some time trying to figure it out. Any help would be extremely appreciated.

**Comment by dillenmeister** [comment]
I quickly looked at how Since.Date works.

This code:

``` csharp
trello.Actions.ForBoard(board, since: Since.Date(DateTime.Parse("2012-01-01")));
```

Will make a GET request to this url:

```
https://trello.com/1/boards/[board_id]/actions?since=2012-01-01 00:00:00&token=[token]&key=[key]
```

Trello.NET does not alter the date, so for now let's assume that Trello.NET works as expected.

It could be that your computer's time and trello.coms time differ. It could also be that trello.com does not publish the actions immediately or caches the actions for a while etc. I think you'll have to do a little more testing to find out what is really going on.

**Comment by bwinters** [comment]
Thank you so much for implementing that so quickly. That solved my problem! I'm setting up a 2 way sync with Trello and another program, and am going to be running the check in as little as a minute, and having all of the time information in Trello, and not having to figure out how to account for variances in time from machine to machine that this may run on works great. Thanks again, and my apologies for not being able to spend the time to figure out how to implement it.

Are you planning on pushing this to NuGet as well?

**Comment by dillenmeister** [comment]
It's on NuGet now!
