### ISSUE TITLE
Assign members to boards

### ISSUE THREAD

**Issue by dillenmeister** [dillenmeister/Trello.NET#18]
Is there a way to invite members to a board or even just assign them as admins/users via the API? I'm trying to automate our project request system so that when a new project is approved a new Trello board is created and my team is assigned as admins to the board.

See: http://stackoverflow.com/questions/14345104/invite-members-to-board-with-trello-net

**Comment by dillenmeister** [comment]
Seems like you use:
[PUT /1/boards/[board_id]/members/[idMember]](https://trello.com/docs/api/board/index.html#put-1-boards-board-id-members-idmember) to add a member to a board
[DELETE /1/boards/[board_id]/members/[idMember]](https://trello.com/docs/api/board/index.html#delete-1-boards-board-id-members-idmember) to remove a member from a board.

**Comment by dillenmeister** [comment]
I'll take a look at this today or some time this week unless someone else wants to take a stab at it.

**Comment by andrewc89** [comment]
I can see if I can do something with it sometime this week. I just didn't know if you had already implemented it and I just couldn't find it.

**Comment by dillenmeister** [comment]
Something like this...

Add member:

``` csharp
Trello.Boards.AddMember(IBoardId board, IMemberId member, BoardMemberType type)
```

Remove member:

``` csharp
Trello.Boards.RemoveMember(IBoardId board, IMemberId member)
```

And the enum:

``` csharp
enum BoardMemberType { Normal, Observer, Admin }
```

Maybe there is a better name than `BoardMemberType` for the enum? `BoardMemberRole`? In the documentation they call the variable `type` though so I don't know...

**Comment by andrewc89** [comment]
Yeah I'd go with `Type` to keep it consistent with their docs.

**Comment by dillenmeister** [comment]
There's also this: [PUT /1/boards/[board_id]/members](https://trello.com/docs/api/board/index.html#put-1-boards-board-id-members) which accepts parameters `email` and `fullname`. I think this what they call a "virtual" member. An invitation e-mail will be sent but the member can be assigned to cards etc. before the invitation is accepted.

Could have an overload for AddMember that looks like this:

``` csharp
Trello.Boards.AddMember(IBoardId board, string email, string fullName, BoardMemberType type)
```

or perhaps like this:

``` csharp
Trello.Boards.AddMember(IBoardId board, VirtualMember member, BoardMemberType type)

class VirtualMember { string Email, string FullName }
```

**Comment by dillenmeister** [comment]
@theyshookhands I will have some time to work with this today unless you want to contribute?

**Comment by andrewc89** [comment]
Yeah I'm working on it right now.

**Comment by dillenmeister** [comment]
Great!

To be able to write a test you might want to have the credentials for the trello user that is used for that. It's easier to see what's going on if you can actually look at the board. A good test for this I think would be one that first adds a member and then removes it (that's how most of the other tests work, they try to clean up after themselves).

I don't think there is a way to send private messages on GitHub and I don't want to type the credentials for the user here. I'm on gmail (dillenmeister), send me an e-mail and I'll give you the credentials.

(Note that most tests regarding notifications are currently broken. It's a known issue...)

**Comment by andrewc89** [comment]
I just noticed for `PUT /1/boards/[board_id]/members/[idMember]` it lists the following as the valid values for `idMember`: A board id, organization id, or organization name.  Am I missing something? Shouldn't a member id be listed?

**Comment by dillenmeister** [comment]
I think that's an error in the documentation. IdMember usually means either the Id or the username of the member.

**Comment by andrewc89** [comment]
Alright I've got a `Boards.AddMember` method for `PUT /1/boards/[board_id]/members/[idMember]`. I still need to do the test and the second method (now that I've got the hang of your design patterns!).

**Comment by andrewc89** [comment]
I just sent you an email from andrew.curcie@gmail btw.

**Comment by andrewc89** [comment]
I don't know what `PUT /1/boards/[board_id]/members` does differently. I tried it on my system and it appears to just add the member. I didn't see any email or anything. I don't know.

**Comment by dillenmeister** [comment]
Answered your e-mail.

On trello.com, if you click Add member... to the right when viewing a board. You first enter an e-mail and then trello.com asks you for the full name. It says in the description text that an invitation email is sent out etc. I think that this API call is for that feature.

You could wait with the `PUT /1/boards/[board_id]/members` and get the other two methods working and send a pull request for them first.

Yeah, regarding design pattenrs you might have noticed that there is an IBoards and also an IAsyncBoards. They have the same methods, except IAsyncBoards returns Task. That's why I have each request as it's own class so it can be reused.

So there will be an `Task Trello.Async.Boards.AddMember` and `Task Trello.Async.Boards.RemoveMember` too. But that's easy, just look at how the other methods are implemented.

**Comment by andrewc89** [comment]
I tried the `AddMembers(board, email, fullName, type)` method on myself so I guess it didn't send an email because I already have a Trello account.

**Comment by dillenmeister** [comment]
Yeah makes sense :)
