### ISSUE TITLE
Getting Actions.ForCard not returning actions of type AddMemberToCardAction

### ISSUE THREAD

**Issue by nfeltch** [dillenmeister/Trello.NET#21]
After assigning a Member to Card I then call _trello.Actions.ForCard(new CardId(<cardId>)) and I do not see an Action of type AddMemberToCardAction.  I do get back an array of Actions, but only of types UpdateCardMoveAction and CommentCardAction.

When I setup my own mock object of ITrello, I can build up an AddMemberToCardAction and it is returned in my unit tests, but when trying to hit the LIVE data on Trello, I never see the AddMemberToCardAction Action.

Please let me know if I'm doing something wrong or if there is a potential bug.

Thanks!

**Comment by dillenmeister** [comment]
Yup, I get the same results. But it does not seem to be a bug in Trello.NET. It's trello.com that doesn't return those action types for a card for some weird reason. It is returned if I use `ForBoard` instead of `ForCard`:

``` csharp
    var actions = trello.Actions.ForBoard(new BoardId("a board id"));
```

So to get the AddMemberToCardActions for a specific card, you could do something like this as a work around:

``` csharp
    var card = trello.Cards.WithId("a card id");
    var actions = trello.Actions
                    .ForBoard(new BoardId(card.IdBoard), new[] { ActionType.AddMemberToCard })
                    .OfType<AddMemberToCardAction>()
                    .Where(a => a.Data.Card.Id == card.Id);
```

You could report a bug with trello.com. This is the api call: `GET /cards/[card_id]/actions`.

**Comment by dillenmeister** [comment]
As a sidenote if you didn't already discover this, Trello uses paging for Actions. So by default you only get 50 actions back (from page 1). There is a `Paging` object you can pass to the methods where you define the limit and the page. 

It's pretty annoying to deal with that so I added an extension method which will get all actions and handle the paging (it will possibly make several calls to trello.com). 

It's used like this:

``` csharp
using TrelloNet.Extensions

var actions = _trelloReadWrite.Actions
    .AutoPaged(Paging.MaxLimit)
    .ForBoard(new BoardId("x"));
```

**Comment by dillenmeister** [comment]
And one more thing, not all type of actions are implemented in Trello.NET (yet). 

Here's a list of the actions trello has: https://trello.com/docs/api/board/index.html#get-1-boards-board-id. 

Compare that with the ActionType enum in Trello.NET to see the ones that are missing,

**Comment by nfeltch** [comment]
Wow, nice quick response!

As I wrote up the issue my gut feeling was this was an integration issue that Trello.com wasn't returning the data, and you confirmed this feeling.  I had that feeling since I had a unit test using your ITrello interface that was working.

Thanks again for confirming my issue and thanks for the workaround by using the Board rather than the Card to get those actions.
