### ISSUE TITLE
Change label names for a board

### ISSUE THREAD

**Issue by dillenmeister** [dillenmeister/Trello.NET#23]
Trello API:
https://trello.com/docs/api/board/index.html#put-1-boards-board-id-labelnames-blue

Requested on SO:
http://stackoverflow.com/questions/12622984/updating-a-trello-board-label-text-with-trello-net

**Comment by andrewc89** [comment]
I can work on this if you haven't already started. I've been waiting for this to be implemented in the API.

**Comment by andrewc89** [comment]
Oh nvm I didn't see your commit there.

**Comment by dillenmeister** [comment]
I beat you to it! 

Any other features you've been missing?

**Comment by andrewc89** [comment]
Nope, that was all I needed.
