### ISSUE TITLE
Getting Activities Since A Specific Date Is Not Predictable

### ISSUE THREAD

**Issue by bgertonson** [dillenmeister/Trello.NET#28]
The format the of the date used in the request to the Trello API is not formatted in a way that results are consistent.

I believe trello expects 2013-12-30T17:45:23.001Z (for Utc, for local replace Z with offset (ex -5:00)).

**Comment by dillenmeister** [comment]
It would not surprise me if there are some date related bugs. Could you provide some more information about this? Maybe create a public board and some code that reproduces the problem?

Or even better, a pull request! If you want to do this I will help you with any questions etc.

**Comment by bgertonson** [comment]
I created this because I had forked the code and corrected it, but then GitHub for Windows botched the line endings. So I tried again this morning. The pull request is pending.

**Comment by dillenmeister** [comment]
Merged!
