### ISSUE TITLE
Update Newtonsoft.Json

### ISSUE THREAD

**Issue by MarioBinder** [dillenmeister/Trello.NET#31]
I try to use Newtonsoft.Json (5.0.3) but I can't install because TrelloNet used a older version (4.5.11).

Isn't Newtonsoft.Json in the dependency packages configured?

**Comment by anelook** [comment]
Hi!

We have the same issue. Any help would be appreciated!

**Comment by andrewc89** [comment]
I made a pull request [here](https://github.com/dillenmeister/Trello.NET/pull/34)

**Comment by dillenmeister** [comment]
Merged!
