### ISSUE TITLE
Determine when a card changed lists

### ISSUE THREAD

**Issue by cpriem** [dillenmeister/Trello.NET#32]
Hi,

Congratulations on such a great library.  I'm trying to implement this stackoverflow question:
http://stackoverflow.com/questions/9812453/trello-api-determine-when-a-card-changed-lists

However, I think I need the listAfter or listBefore from the listUpdate actions and I can't find where this is.  Do you have any suggestions on how to do this, or is this not yet implemented in the library?

Thanks!

**Comment by dillenmeister** [comment]
It should be possible. (Untested code below!)

``` csharp
var card = trello.Cards.WithId("a card id");

var cardMoves = trello.Actions
    .ForCard(card)
    .OfType<UpdateCardMoveAction>();

foreach (var cardMove in cardMoves)
{
    Console.WriteLine("Card moved from {0} to {1}.",
        cardMove.Data.ListBefore,
        cardMove.Data.ListAfter);
}
```

I would probably write the second statement like this though:

``` csharp
var cardMoves = trello.Actions
    .AutoPaged() // Use this extension method and Trello.NET handles paging
    .ForCard(card, new [] { ActionType.UpdateCard }) // Reduces response size
    .OfType<UpdateCardMoveAction>();
```

**Comment by cpriem** [comment]
works awesome, thanks so much, I owe you a beer!
