### ISSUE TITLE
Checklists - Pos

### ISSUE THREAD

**Issue by pauldbentley** [dillenmeister/Trello.NET#36]
Hi,

Could you add support for the Pos property on both Checklist and CheckItem.

The Trello API doesn't seem to return them in the correct order and I am building an application which needs them to be in the same order as in Trello.

Thanks

Paul

**Comment by andrewc89** [comment]
Is anyone working on this? I have some time this week during which I could work on it.

**Comment by dillenmeister** [comment]
As far as I know, no one is working on this so please go ahead. If it's just new properties on checklist and checkitem this should be very easy (just add the Pos property to the classes and Json.NET will deserialize them).

19 aug 2013 kl. 16:03 skrev gwely notifications@github.com:

**Comment by andrewc89** [comment]
I am also trying to fix the failing tests. You had sent me the login info previously but it seems as if the Welcome Board the tests are using is not a board accessible by the user I am using. I can open a new issue for fixing the tests and/or you can email me the creds for the correct board at [removed]

**Comment by dillenmeister** [comment]
I fixed the tests about three weeks ago and all the tests still pass for me now when I run them. Are you sure you have the latest source?

I sent you the credentials for the test accounts. I don't think you need them for this, but you never know :).

**Comment by andrewc89** [comment]
Whoops! I hadn't synced correctly. Looks good.

**Comment by dillenmeister** [comment]
Thanks!
