### ISSUE TITLE
Get Public Trello Board WITHOUT AuthorizationToken

### ISSUE THREAD

**Issue by diiigle** [dillenmeister/Trello.NET#38]
I tried to read a [public board](https://trello.com/b/RjsWYYLN) without prior authorization, but my call to

``` C#
Trello trelloAPI = new Trello("<my API key>");
Board updateBoard = trelloAPI.Boards.WithId("5245a378c49bbb017d003a93");
```

only returns null.

When i add a AuthToken, Trello.NET returns the right object.
Its not the fault of the Trello API, i can fetch the JSON in my browser.

I installed Trello.NET via NuGet so i am not able to debug it myself. I'll pull the sources soon, but maybe you know a solution, that makes that process unnecessary.

**Comment by dillenmeister** [comment]
It was a bug. I fixed it and released a new version so you should be able to NuGet it and try it out.

**Comment by diiigle** [comment]
Wow,  thank you for that fast fix! I try to build a Bug Reporter / Notification Manager for [open3mod](/diiigle/open3mod) on top of Trello, FYI.
