### ISSUE TITLE
Wrong date format when culture not is en-US

### ISSUE THREAD

**Issue by tjanssens** [dillenmeister/Trello.NET#4]
When the culture for the application is not set to en-US, the date is serialized wrong.
example: when the due date is set to 11 may 2012 when the cultrue is nl-BE, in Trello the due date for the card is set to 5 november 2012

so the serialization for Date has to be MM/dd/yyyy no matter what the culture is.

Kind regards,
Tom

**Comment by dillenmeister** [comment]
I've made a fix for this (60f54f79a021a195fc9bed57f7a40304a8b96618). I also updated the NuGet package. Please try it out and let me know if it works as expected.

**Comment by tjanssens** [comment]
Thank you very much, you saved my day!
