### ISSUE TITLE
WANT TO GET THE CARD CREATION DATE AND TIME

### ISSUE THREAD

**Issue by ahsanmuneer3910** [dillenmeister/Trello.NET#42]
hi
I WANT TO GET THE CARD CREATION DATE AND TIME.I need help from you.
Thanks

**Comment by danesparza** [comment]
You need to look for the 'CreateCardAction' for the cardId in question.  Trello uses an 'event history' paradigm for storing information like this.  It's similar to a [command pattern](http://en.wikipedia.org/wiki/Command_pattern) but for storing history.
