### ISSUE TITLE
Cards.AddLabel does not add label to card

### ISSUE THREAD

**Issue by mikeberlin** [dillenmeister/Trello.NET#48]
I am able to create a card with no issues.  I am also able to add file attachments after the card is created.  However, I am not able to assign a Label to a card through the API.  I'm using the following method with no luck:

ITrello trelloAPI = new Trello(TrelloAppKey);
... authentication and whatnot...
trelloAPI.Cards.AddLabel(newCard, Color.Orange);

I place a breakpoint directly after the AddLabel method call and see no Labels in  newCard, I also do not see the Label in the Trello board.

Any ideas?

**Comment by mikeberlin** [comment]
It appears that since I was calling

trelloAPI.Cards.Update(newCard);

later in my code it would not save my label. I have removed this line of code and the label is successfully added.  Any ideas why the Update method would delete the labels from the card?

**Comment by bmccabe** [comment]
This seems to still be a problem. Update(trelloCard) drops the labels. You have to re add them:

```
    foreach (Card.Label L in trelloCard.Labels) {
        myTrello.Cards.AddLabel(trelloCard, L.Color);
    }
```

**Comment by dillenmeister** [comment]
This is a breaking change if you've implemented `IUpdatableCard` yourself since it has a new member. If you use `Card`, it's fine.
