### ISSUE TITLE
implement search function

### ISSUE THREAD

**Issue by paulduran** [dillenmeister/Trello.NET#5]
Hi,

I really like the Trello API wrapper that you have built so far.

I'd love it if you were able to implement the trello search function - https://trello.com/docs/api/search/index.html#get-1-search

I spent some time looking at the source code to see if it would be easy for me to code the functionality and submit a pull request however it didn't seem very straightforward to me, not knowing your code base very well.

regards,
Paul.

**Comment by dillenmeister** [comment]
Yes, the new search function should definately be in Trello.NET! I'll give it a go this week.

**Comment by dillenmeister** [comment]
I made an implementation of the search functionality. It's used like this:

```
var cards = trello.Cards.Search("something");
```

Similar for Boards, Organizations, Members and Actions. And there's also a method `trello.Search` which searches in all those models.

Try it out: `Install-Package TrelloNet -Pre`.

Let me know if you find any bugs or if you have suggestions on how to improve the API.

**Comment by paulduran** [comment]
Wow that's a great turnaround time!

I was hoping to be able to search for cards within a particular list. Do you know if there's a way to do that with the search API?

What I implemented (before you published your updated package) was something like:

```
    var existing = trello.Cards.ForList(listId, CardFilter.All);
    return existing.FirstOrDefault(x => x.Name.Contains(searchText));
```

But if I can leverage the search API to do it, that would be preferred

**Comment by dillenmeister** [comment]
It does not seem possible to search for cards in a specific list, but it is possible to search in specific boards. I don't know if that helps, but here's a way to do it with Trello.NET:

``` csharp
    var listToSearch = trello.Lists.WithId(listId);
    var searchFilter = new SearchFilter { Boards = new[] { new BoardId(listToSearch.IdBoard) } };
    var cards = trello.Cards.Search(searchText, filter: searchFilter);
    return cards.Where(c => c.IdList == listToSearch.Id);
```

Your current implementation might be faster though.
