### ISSUE TITLE
Cards.SendToBoard function does not SendToBoard

### ISSUE THREAD

**Issue by RobboAU** [dillenmeister/Trello.NET#9]
Attempting to use 0.5.5-beta (from NuGet) to move a Card from one Board to another.

Is this the correct method to use?

```
TrelloNet.Trello.Cards.SendToBoard(TrelloNet.Card)
```

If not, what is the correct method to Move a Card to a new Board? Where do you specify the BoardID to send the Card to?

Thanks

**Comment by dillenmeister** [comment]
`SendToBoard` is for returning an archived card to it's board. Moving a card between boards is not implemented in Trello.NET. I can probably fix that for tomorrow though.

The reason it's called SendToBoard is because that's what the button on trello.com says. But renaming the method to `Unarchive` is a good idea right?

**Comment by dillenmeister** [comment]
I've added a new overload to the Move method:
`Trello.Cards.Move(ICardId card, IBoardId board, IListId list = null)`

Try it out. https://nuget.org/packages/TrelloNet/0.5.5-beta2

**Comment by RobboAU** [comment]
> I can probably fix that for tomorrow though.

Thanks for the rapid response, I appreciate you implementing this feature so quickly.

> The reason it's called SendToBoard is because that's what the button on trello.com says. But renaming the method >to Unarchive is a good idea right?

That is a good idea, and I like how you have implemented it now.

> I've added a new overload to the Move method:
> Trello.Cards.Move(ICardId card, IBoardId board, IListId list = null)
> 
> Try it out. https://nuget.org/packages/TrelloNet/0.5.5-beta2

I've brought the new package in and it works perfectly. My application is already moving cards from board to board. 

While I don't require it for this implementation, I also appreciate the optional ListID variable that mirrors the buttons on trello.com
